---
abstract: 'Ease-of-use functions for perl core Types'
author:
  - 'LAWALSH (LAWALSH@cpan.org)'
build_requires:
  Test::Simple: 0.44
  Xporter: v0.0.4
  mem: v0.3.2
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.82, CPAN::Meta::Converter version 2.132830'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Types-Core
no_index:
  directory:
    - t
    - inc
requires:
  Xporter: v0.0.4
  mem: v0.3.2
version: v0.1.2
